### PR TITLE
 issue ipedrazas#68 add stable_repo_url to change default stable repository

### PR DESCRIPTION
**Pull request by Kayuii**

### CODE REVIEW

**Comment by josmo** [comment]
@Kayuii thanks for the PR however this is a fork from the main repo. I'm more then happy to merge and publish it (or pull in changes from ipdrazas if you want to use the image I publish) :) . Let me know what you'd rather :)

**Comment by josmo** [comment]
Hi @Kayuii I pulled the changes from the upstream and published an image tag for it :)

**Comment by Kayuii** [comment]
thk！ @josmo   I still have some problems when using plug-ins. What I am using now is https://github.com/ystyle/drone-plugin-rancher2.git. Does drone-helm have a detailed reference for the use of this plug-in in rancher 2? The configuration file of k8s still prompts me to log in to the client.

**Comment by josmo** [comment]
@Kayuii using the helm plugin with rancher 2 is pretty straight forward. If it's still asking you for creds make sure to add the following env variables secrets
kubernetes_token and api_server - the token is the user token in the kubeconfig file for the cluster and the api_server is the cluster server url (you can find those in the rancher ui for the cluster and the button that says kubeconfig file)

**Pull request merged**
